# Generated by Django 3.2.4 on 2021-06-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210619_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='batch',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
        ),
    ]
