# Generated by Django 3.2.4 on 2021-06-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210620_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='student',
        ),
    ]
