# Generated by Django 3.2.4 on 2021-06-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_batch_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
