# Generated by Django 3.2.4 on 2021-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_batch_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='student',
            field=models.ManyToManyField(to='users.Student'),
        ),
    ]
