# Generated by Django 3.2.4 on 2021-06-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_batch_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='student',
            new_name='students',
        ),
    ]
