# Generated by Django 3.2.4 on 2021-06-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_student_batch_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='completed_classes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='total_classes',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
