# Generated by Django 3.2.4 on 2021-06-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210620_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
