# Generated by Django 3.2.4 on 2021-06-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_batch_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='students',
        ),
    ]
